package com.clearpath.backend.dto.phase1;

import java.util.List;
import java.util.Map;

/**
 * CheatsheetResponse
 *
 * Responsibility: Define the structure of the Cheatsheet returned to the frontend
 *
 * This is the final output of the entire pipeline:
 * session → SessionValidator → AIPromptBuilder → AI → CheatsheetResponse
 */
public class CheatsheetResponse {

    // Who the user is
    private Map<String, String> profile;

    // What the user needs to do (ordered list of actionable steps)
    private List<Map<String, Object>> steps;

    // Important things the user must be aware of
    private List<String> warnings;

    // Personalized notes generated by AI based on user's specific situation
    private String aiNotes;

    public Map<String, String> getProfile() { return profile; }
    public void setProfile(Map<String, String> profile) { this.profile = profile; }

    public List<Map<String, Object>> getSteps() { return steps; }
    public void setSteps(List<Map<String, Object>> steps) { this.steps = steps; }

    public List<String> getWarnings() { return warnings; }
    public void setWarnings(List<String> warnings) { this.warnings = warnings; }

    public String getAiNotes() { return aiNotes; }
    public void setAiNotes(String aiNotes) { this.aiNotes = aiNotes; }
}