spring.application.name=clearpath-backend

spring.datasource.url=jdbc:h2:mem:clearpathdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

anthropic.api.key=AIzaSyDXXp6y7a6IQqlIBbailb2-4-S4J2_d1Ys