package com.clearpath.backend;

import java.util.List;
import java.util.Map;

/**
 * CheatsheetResponse
 *
 * Responsibility: Define the structure of the Cheatsheet returned to the frontend
 *
 * This is the final output of the entire pipeline:
 * session → SessionValidator → AIPromptBuilder → AI → CheatsheetResponse
 *
 * Fields:
 * - profile:  Who the user is (status, permit situation, foreign license, experience)
 * - steps:    What the user needs to do (ordered list of actionable steps)
 * - warnings: Important things the user must be aware of
 * - aiNotes:  Personalized notes generated by AI based on user's specific situation
 *
 * Each step contains:
 * - stepId:      Unique identifier
 * - title:       Short title of the step
 * - description: Detailed explanation
 * - documents:   List of documents required for this step
 * - guide:       Detailed operational guide from GuideLibrary
 */
public class CheatsheetResponse {

    private Map<String, String> profile;
    private List<Map<String, Object>> steps;
    private List<String> warnings;
    private String aiNotes;

    // TODO: Getters and Setters

}